create database scm  default character set utf8;
CREATE USER 'scm'@'%' IDENTIFIED BY 'scm';
GRANT ALL PRIVILEGES ON scm. * TO 'scm'@'%';
create database amon  default character set utf8;
CREATE USER 'amon'@'%' IDENTIFIED BY 'amon';
GRANT ALL PRIVILEGES ON amon. * TO 'amon'@'%';
create database rman  default character set utf8;
CREATE USER 'rman'@'%' IDENTIFIED BY 'rman';
GRANT ALL PRIVILEGES ON rman. * TO 'rman'@'%';
create database hue  default character set utf8;
CREATE USER 'hue'@'%' IDENTIFIED BY 'hue';
GRANT ALL PRIVILEGES ON hue. * TO 'hue'@'%';
create database metastore  default character set utf8;
CREATE USER 'hive'@'%' IDENTIFIED BY 'hive';
GRANT ALL PRIVILEGES ON metastore. * TO 'hive'@'%';
create database sentry  default character set utf8;
CREATE USER 'sentry'@'%' IDENTIFIED BY 'sentry';
GRANT ALL PRIVILEGES ON sentry. * TO 'sentry'@'%';
create database nav  default character set utf8;
CREATE USER 'nav'@'%' IDENTIFIED BY 'nav';
GRANT ALL PRIVILEGES ON nav. * TO 'nav'@'%';
create database navms  default character set utf8;
CREATE USER 'navms'@'%' IDENTIFIED BY 'navms';
GRANT ALL PRIVILEGES ON navms. * TO 'navms'@'%';
create database oozie  default character set utf8;
CREATE USER 'oozie'@'%' IDENTIFIED BY 'oozie';
GRANT ALL PRIVILEGES ON oozie. * TO 'oozie'@'%';
FLUSH PRIVILEGES;